### ISSUE TITLE
uieditor Cannot open include file: 'eg.h': No such file or directory

### ISSUE THREAD

**Issue by wighawag** [Daivuk/onut#2]
Hi, I was interested in your editor (from the youtube video) and wanted to try it out. After opening the visual studio solution I get the following error :
Cannot open include file: 'eg.h': No such file or directory

The sub project "egdx11 is marked as unavailable.

any idea?

Thanks

**Comment by Daivuk** [comment]
Oh haha
I didn't think someone will try it out. It's really not ready for public.

What you need is to clone EasyGraphix into onut.
That's Another one of my repo.

The editor is missing tons of features. You cannot create new files. You have to start with a file. (You can copy the editor one, then delete everything and save)

You can't multi select. You can't scroll or zoom.

Envoyé de mon iPhone

**Comment by wighawag** [comment]
I am currently looking for some ui editor I can use to create some game ui and found your on youtube.
Added EasyGraphics and now I get some linkign error :

1>  egdx11.lib(egdx11.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
1>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification
1>DocumentView.obj : warning LNK4075: ignoring '/EDITANDCONTINUE' due to '/OPT:LBR' specification
1>onut.lib(ActionManager.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(StringUtils.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(input.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(UI.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(SpriteBatch.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(Window.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(onut.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(Renderer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(Settings.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(SimpleMath.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(Texture.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(BMFont.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(Anim.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(AudioEngine.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(InputDevice.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(EventManager.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(GamePad.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(ParticleEmitter.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(Random.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(PrimitiveBatch.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(LodePNG.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(SoundCommon.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>onut.lib(Particle.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(ios.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(locale0.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(iosptrs.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(locale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(xlock.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(xthrow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(wlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(xlocale.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>libcpmtd.lib(xdateord.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in DocumentView.obj
1>LIBCMTD.lib(crt0init.obj) : error LNK2005: ___xi_a already defined in MSVCRTD.lib(cinitexe.obj)
1>LIBCMTD.lib(crt0init.obj) : error LNK2005: ___xi_z already defined in MSVCRTD.lib(cinitexe.obj)
1>LIBCMTD.lib(crt0init.obj) : error LNK2005: ___xc_a already defined in MSVCRTD.lib(cinitexe.obj)
1>LIBCMTD.lib(crt0init.obj) : error LNK2005: ___xc_z already defined in MSVCRTD.lib(cinitexe.obj)
1>LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
1>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library
1>C:\experiments\onut\uieditor\project\win\Debug\uieditor.exe : fatal error LNK1169: one or more multiply defined symbols found

Don't bother if the ui editor is not ready, I ll look somehwere else

All the best

**Comment by Daivuk** [comment]
I should try to make it ready, and fix the remaining issues...
Even if its not 100% complete.
I find it so useful I am making all my game UI with it. And in game it's
easy to integrate in any engine.

Are you on windows 8.1? I haven't try to compile on other platforms.
If you cloned EG into the onut folder, you should be good. Open the editor
visual studio solution. I use this solution daily and push it when I change
stuff.

You have a mismatch with the DLL vs Static library. Make sure all projects
are set to static. (But they should be already...)

**Comment by Daivuk** [comment]
I will clone this on my windows 7 laptop tonight maybe and give it a shot.

**Comment by Daivuk** [comment]
What are the features you need for your game?

This UI is more for complex games. Like MMO, Civilization type games, etc.
If you try to make scaling/rotation, this won't do. Like casual gaming.

I can try and focus on fixing it. You're the first one that is trying to
use it. Stuff I would focus on fixing/finishing for now would be:

_Missing features of the UI API:_
- Scroll view (very important)
- Sliders
- Textbox are a bit hard to setup from code for now.

_Missing editor features:_
- Multi select
- Reordering (I usually cut/paste to achieve that)
- Creating new files (Need to start from a template)
- Scroll views (Can't scroll the hierarchy view, need to collapse top items
  to see bottom ones)
- Font needs a .fnt files. All the other font options are currently ignored
  by the editor.
- Panning/Zoom the editor view
- A .exe instead of having you trying to build it :)

**Comment by Daivuk** [comment]
Correction:
_> If you try to make scaling/rotation, this won't do._
You can actually define custom styles and override how they render so
technically that's not an issue.

**Comment by wighawag** [comment]
I am on windows 7,
I need 
- images (with scale options : keeping ratio / scale9 / fixed)
- container that can have image as background (with scale options) 
  container should provide layout option as well
- text (font)
- item can be rotated

So maybe  your editor could be worth a try, especially since it is open source.

But in the end I might make my own :)

**Comment by Daivuk** [comment]
_images (with scale options : keeping ratio / scale9 / fixed)_

I would need to add "scale but keep ratio" feature, the rest is supported.

_container that can have image as background (with scale options) container
should provide layout option as well_

Everything is a containers.
I don't have automatic layout options yet. But shouldn't be too hard to
add. Like _VerticalLayout_, _HorizontalLayout_, *GridLayout *?

_text (font)_

The UI will _not *render fonts for you. Actually it doesn't render anything
for you. (It's the whole point). You get a callback saying: Please render
text here, with that rectangle. And in argument you get a struct with all
the info on the text. Then one could use a bitmap font, or draw font
directly to texture using FreeType2 or something similar. I use one of my
other repo for that: *dfr_

_item can be rotated_

Onut UI are only rectangle. They don't have a matrix transform. But since
you can override styles, you can do what you want. But it won't affect
children

You can also make your own editor :D
It's always fun thing to do.
In the end, my editor spits out a json file. So it's readable.

But you inspired me to try to fix mine for now. And provide a downloadable
executable for win7/win8.1
Maybe more people will want to use it in the future.

Thanks,
David

**Comment by wighawag** [comment]
Cool, the fact you have a json export option interest me. I ll make sure to test it when it is ready.
All the best,

**Comment by Daivuk** [comment]
The flag was set wrong in the UIEditor project. I changed the flag recently
in onut without fixing the editor.
It compiles fine now (In debug). I pushed the fix.

But I'll do more serious fixes now.

Btw, do you have a website or youtube channel or cool projects you worked
on? I say your github seems pretty busy.

**Comment by Daivuk** [comment]
Been resolved. EasyGraphix has been disabled by default and probably won't be maintained in the future. We're back to onut own renderer.
